using AutopartsEntity.Catalog.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace AutopartsRepository.Configurations.Catalog
{
    public class BrandConfig : IEntityTypeConfiguration<Brand>
    {
        public void Configure(EntityTypeBuilder<Brand> builder)
        {
            builder.Property(x => x.CreateDate).IsRequired()
                .HasMaxLength(10);
            builder.Property(x => x.UpdateDate)
                .HasMaxLength(10);
            builder.Property(x => x.RowVersion)
                .IsRowVersion();

            builder.Property(x => x.TecDoc)
                .HasMaxLength(6);
            builder.Property(x => x.BrandName).IsRequired()
                .HasMaxLength(50);
            builder.Property(x => x.LogoPath)
                .HasMaxLength(500);
            builder.Property(x => x.IsActive)
                .HasDefaultValue(false);
            builder.Property(x => x.BrandDescription)
                .HasMaxLength(2000);

            builder.HasData(
                new Brand { Id = 1, TecDoc = 1, BrandName = "SPIDAN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 2, TecDoc = 2, BrandName = "HELLA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 3, TecDoc = 3, BrandName = "ATE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 4, TecDoc = 4, BrandName = "MANN-FILTER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 5, TecDoc = 5, BrandName = "PIERBURG", IsActive = true, BrandDescription = "" },
                new Brand { Id = 6, TecDoc = 6, BrandName = "LuK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 7, TecDoc = 7, BrandName = "EBERSPÄCHER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 8, TecDoc = 9, BrandName = "VICTOR REINZ", IsActive = true, BrandDescription = "" },
                new Brand { Id = 9, TecDoc = 10, BrandName = "ELRING", IsActive = true, BrandDescription = "" },
                new Brand { Id = 10, TecDoc = 11, BrandName = "BorgWarner (BERU)", IsActive = true, BrandDescription = "" },
                new Brand { Id = 11, TecDoc = 13, BrandName = "WALKER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 12, TecDoc = 15, BrandName = "NGK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 13, TecDoc = 16, BrandName = "BILSTEIN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 14, TecDoc = 18, BrandName = "KONI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 15, TecDoc = 19, BrandName = "SWF", IsActive = true, BrandDescription = "" },
                new Brand { Id = 16, TecDoc = 21, BrandName = "VALEO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 17, TecDoc = 23, BrandName = "RUVILLE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 18, TecDoc = 24, BrandName = "EXIDE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 19, TecDoc = 26, BrandName = "VARTA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 20, TecDoc = 29, BrandName = "ERNST", IsActive = true, BrandDescription = "" },
                new Brand { Id = 21, TecDoc = 30, BrandName = "BOSCH", IsActive = true, BrandDescription = "" },
                new Brand { Id = 22, TecDoc = 31, BrandName = "CONTINENTAL CTAM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 23, TecDoc = 32, BrandName = "SACHS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 24, TecDoc = 33, BrandName = "GATES", IsActive = true, BrandDescription = "" },
                new Brand { Id = 25, TecDoc = 34, BrandName = "KNECHT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 26, TecDoc = 35, BrandName = "LEMFÖRDER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 27, TecDoc = 36, BrandName = "VAN WEZEL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 28, TecDoc = 37, BrandName = "MONROE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 29, TecDoc = 38, BrandName = "PURFLUX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 30, TecDoc = 39, BrandName = "TEXTAR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 31, TecDoc = 41, BrandName = "BOSAL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 32, TecDoc = 42, BrandName = "DAYCO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 33, TecDoc = 43, BrandName = "CHAMPION", IsActive = true, BrandDescription = "" },
                new Brand { Id = 34, TecDoc = 47, BrandName = "BREMI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 35, TecDoc = 48, BrandName = "JURID", IsActive = true, BrandDescription = "" },
                new Brand { Id = 36, TecDoc = 50, BrandName = "SKF", IsActive = true, BrandDescription = "" },
                new Brand { Id = 37, TecDoc = 51, BrandName = "WESTFALIA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 38, TecDoc = 54, BrandName = "FTE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 39, TecDoc = 55, BrandName = "HERTH+BUSS JAKOPARTS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 40, TecDoc = 56, BrandName = "LÖBRO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 41, TecDoc = 57, BrandName = "QUINTON HAZELL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 42, TecDoc = 61, BrandName = "TYC", IsActive = true, BrandDescription = "" },
                new Brand { Id = 43, TecDoc = 65, BrandName = "BREMBO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 44, TecDoc = 66, BrandName = "DENSO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 45, TecDoc = 67, BrandName = "ams-OSRAM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 46, TecDoc = 68, BrandName = "ZF", IsActive = true, BrandDescription = "" },
                new Brand { Id = 47, TecDoc = 72, BrandName = "HERTH+BUSS ELPARTS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 48, TecDoc = 75, BrandName = "PHILIPS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 49, TecDoc = 78, BrandName = "KLOKKERHOLM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 50, TecDoc = 79, BrandName = "BorgWarner (Wahler)", IsActive = true, BrandDescription = "" },
                new Brand { Id = 51, TecDoc = 81, BrandName = "HENGST FILTER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 52, TecDoc = 83, BrandName = "CONTINENTAL/VDO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 53, TecDoc = 85, BrandName = "KYB", IsActive = true, BrandDescription = "" },
                new Brand { Id = 54, TecDoc = 86, BrandName = "ZIMMERMANN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 55, TecDoc = 88, BrandName = "GLASER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 56, TecDoc = 89, BrandName = "DELPHI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 57, TecDoc = 94, BrandName = "METZGER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 58, TecDoc = 95, BrandName = "MAGNETI MARELLI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 59, TecDoc = 97, BrandName = "WAECO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 60, TecDoc = 101, BrandName = "FEBI BILSTEIN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 61, TecDoc = 106, BrandName = "BRINK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 62, TecDoc = 109, BrandName = "BUGATTI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 63, TecDoc = 110, BrandName = "SNR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 64, TecDoc = 112, BrandName = "EIBACH", IsActive = true, BrandDescription = "" },
                new Brand { Id = 65, TecDoc = 113, BrandName = "PAYEN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 66, TecDoc = 114, BrandName = "BUDWEG CALIPER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 67, TecDoc = 115, BrandName = "ULO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 68, TecDoc = 117, BrandName = "LRT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 69, TecDoc = 118, BrandName = "HJS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 70, TecDoc = 121, BrandName = "METELLI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 71, TecDoc = 123, BrandName = "NISSENS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 72, TecDoc = 126, BrandName = "STABILUS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 73, TecDoc = 127, BrandName = "NK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 74, TecDoc = 129, BrandName = "OPTIMAL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 75, TecDoc = 135, BrandName = "SIDEM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 76, TecDoc = 137, BrandName = "UFI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 77, TecDoc = 138, BrandName = "JOHNS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 78, TecDoc = 139, BrandName = "AJUSA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 79, TecDoc = 140, BrandName = "CORTECO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 80, TecDoc = 141, BrandName = "AE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 81, TecDoc = 142, BrandName = "SOFIMA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 82, TecDoc = 144, BrandName = "MEYLE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 83, TecDoc = 151, BrandName = "SWAG", IsActive = true, BrandDescription = "" },
                new Brand { Id = 84, TecDoc = 154, BrandName = "DOLZ", IsActive = true, BrandDescription = "" },
                new Brand { Id = 85, TecDoc = 156, BrandName = "JAPANPARTS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 86, TecDoc = 158, BrandName = "ICER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 87, TecDoc = 159, BrandName = "FACET", IsActive = true, BrandDescription = "" },
                new Brand { Id = 88, TecDoc = 161, BrandName = "TRW", IsActive = true, BrandDescription = "" },
                new Brand { Id = 89, TecDoc = 162, BrandName = "VAICO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 90, TecDoc = 166, BrandName = "AISIN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 91, TecDoc = 167, BrandName = "DUPLI COLOR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 92, TecDoc = 168, BrandName = "MOTIP", IsActive = true, BrandDescription = "" },
                new Brand { Id = 93, TecDoc = 169, BrandName = "PRESTO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 94, TecDoc = 175, BrandName = "LESJÖFORS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 95, TecDoc = 177, BrandName = "BTS Turbo", IsActive = true, BrandDescription = "" },
                new Brand { Id = 96, TecDoc = 178, BrandName = "HEPU", IsActive = true, BrandDescription = "" },
                new Brand { Id = 97, TecDoc = 180, BrandName = "ALCO FILTER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 98, TecDoc = 181, BrandName = "GK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 99, TecDoc = 182, BrandName = "SCHLÜTTER TURBOLADER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 100, TecDoc = 183, BrandName = "VEMO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 101, TecDoc = 185, BrandName = "KAMOKA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 102, TecDoc = 191, BrandName = "IMASAF", IsActive = true, BrandDescription = "" },
                new Brand { Id = 103, TecDoc = 192, BrandName = "FAG", IsActive = true, BrandDescription = "" },
                new Brand { Id = 104, TecDoc = 197, BrandName = "LPR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 105, TecDoc = 198, BrandName = "OCAP", IsActive = true, BrandDescription = "" },
                new Brand { Id = 106, TecDoc = 202, BrandName = "GLYCO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 107, TecDoc = 204, BrandName = "INA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 108, TecDoc = 205, BrandName = "NRF", IsActive = true, BrandDescription = "" },
                new Brand { Id = 109, TecDoc = 206, BrandName = "A.B.S.", IsActive = true, BrandDescription = "" },
                new Brand { Id = 110, TecDoc = 207, BrandName = "CASTROL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 111, TecDoc = 209, BrandName = "TRUCKTEC AUTOMOTIVE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 112, TecDoc = 214, BrandName = "REMY", IsActive = true, BrandDescription = "" },
                new Brand { Id = 113, TecDoc = 215, BrandName = "CALORSTAT by Vernet", IsActive = true, BrandDescription = "" },
                new Brand { Id = 114, TecDoc = 216, BrandName = "NÜRAL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 115, TecDoc = 220, BrandName = "AIRTEX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 116, TecDoc = 222, BrandName = "LIQUI MOLY", IsActive = true, BrandDescription = "" },
                new Brand { Id = 117, TecDoc = 225, BrandName = "SCT - MANNOL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 118, TecDoc = 226, BrandName = "ELSTOCK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 119, TecDoc = 233, BrandName = "DINEX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 120, TecDoc = 234, BrandName = "ERA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 121, TecDoc = 235, BrandName = "FRECCIA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 122, TecDoc = 240, BrandName = "FAE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 123, TecDoc = 244, BrandName = "MEAT & DORIA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 124, TecDoc = 247, BrandName = "AVA QUALITY COOLING", IsActive = true, BrandDescription = "" },
                new Brand { Id = 125, TecDoc = 248, BrandName = "NIPPARTS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 126, TecDoc = 256, BrandName = "FILTRON", IsActive = true, BrandDescription = "" },
                new Brand { Id = 127, TecDoc = 257, BrandName = "ASHIKA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 128, TecDoc = 260, BrandName = "SASIC", IsActive = true, BrandDescription = "" },
                new Brand { Id = 129, TecDoc = 267, BrandName = "FAI AutoParts", IsActive = true, BrandDescription = "" },
                new Brand { Id = 130, TecDoc = 268, BrandName = "JP GROUP", IsActive = true, BrandDescription = "" },
                new Brand { Id = 131, TecDoc = 277, BrandName = "AMC", IsActive = true, BrandDescription = "" },
                new Brand { Id = 132, TecDoc = 287, BrandName = "MAHLE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 133, TecDoc = 294, BrandName = "SACHS PERFORMANCE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 134, TecDoc = 295, BrandName = "fri.tech.", IsActive = true, BrandDescription = "" },
                new Brand { Id = 135, TecDoc = 297, BrandName = "sbs", IsActive = true, BrandDescription = "" },
                new Brand { Id = 136, TecDoc = 299, BrandName = "WEBASTO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 137, TecDoc = 300, BrandName = "AUTEX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 138, TecDoc = 301, BrandName = "TOPRAN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 139, TecDoc = 305, BrandName = "K&N Filters", IsActive = true, BrandDescription = "" },
                new Brand { Id = 140, TecDoc = 310, BrandName = "GRAF", IsActive = true, BrandDescription = "" },
                new Brand { Id = 141, TecDoc = 311, BrandName = "CIFAM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 142, TecDoc = 316, BrandName = "GENERAL RICAMBI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 143, TecDoc = 323, BrandName = "AUTOMEGA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 144, TecDoc = 324, BrandName = "WIX FILTERS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 145, TecDoc = 326, BrandName = "BorgWarner (Schwitze", IsActive = true, BrandDescription = "" },
                new Brand { Id = 146, TecDoc = 327, BrandName = "BorgWarner", IsActive = true, BrandDescription = "" },
                new Brand { Id = 147, TecDoc = 328, BrandName = "BorgWarner (3K)", IsActive = true, BrandDescription = "" },
                new Brand { Id = 148, TecDoc = 331, BrandName = "ORIGINAL IMPERIUM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 149, TecDoc = 340, BrandName = "PRASCO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 150, TecDoc = 347, BrandName = "TRW Engine Component", IsActive = true, BrandDescription = "" },
                new Brand { Id = 151, TecDoc = 350, BrandName = "BLUE PRINT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 152, TecDoc = 351, BrandName = "AUTOFREN SEINSA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 153, TecDoc = 356, BrandName = "TESLA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 154, TecDoc = 362, BrandName = "ALKAR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 155, TecDoc = 367, BrandName = "FA1", IsActive = true, BrandDescription = "" },
                new Brand { Id = 156, TecDoc = 373, BrandName = "GSP", IsActive = true, BrandDescription = "" },
                new Brand { Id = 157, TecDoc = 376, BrandName = "CENTRA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 158, TecDoc = 377, BrandName = "BOSCH DIAGNOSTICS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 159, TecDoc = 380, BrandName = "FRENKIT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 160, TecDoc = 385, BrandName = "GOETZE ENGINE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 161, TecDoc = 388, BrandName = "MOTORAD", IsActive = true, BrandDescription = "" },
                new Brand { Id = 162, TecDoc = 389, BrandName = "GLYSANTIN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 163, TecDoc = 391, BrandName = "EAI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 164, TecDoc = 394, BrandName = "BARUM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 165, TecDoc = 397, BrandName = "JANMOR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 166, TecDoc = 399, BrandName = "EXEDY", IsActive = true, BrandDescription = "" },
                new Brand { Id = 167, TecDoc = 400, BrandName = "RAICAM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 168, TecDoc = 403, BrandName = "MAXGEAR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 169, TecDoc = 406, BrandName = "BM CATALYSTS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 170, TecDoc = 409, BrandName = "FREMAX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 171, TecDoc = 427, BrandName = "ASMET", IsActive = true, BrandDescription = "" },
                new Brand { Id = 172, TecDoc = 430, BrandName = "RTS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 173, TecDoc = 432, BrandName = "KOLBENSCHMIDT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 174, TecDoc = 433, BrandName = "STATIM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 175, TecDoc = 436, BrandName = "MOTUL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 176, TecDoc = 437, BrandName = "CoopersFiaam", IsActive = true, BrandDescription = "" },
                new Brand { Id = 177, TecDoc = 443, BrandName = "ENERGIZER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 178, TecDoc = 447, BrandName = "PILKINGTON", IsActive = true, BrandDescription = "" },
                new Brand { Id = 179, TecDoc = 449, BrandName = "HITACHI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 180, TecDoc = 454, BrandName = "BANDO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 181, TecDoc = 460, BrandName = "DRI", IsActive = true, BrandDescription = "" },
                new Brand { Id = 182, TecDoc = 461, BrandName = "RAVENOL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 183, TecDoc = 464, BrandName = "OSVAT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 184, TecDoc = 467, BrandName = "CS Germany", IsActive = true, BrandDescription = "" },
                new Brand { Id = 185, TecDoc = 475, BrandName = "BORG & BECK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 186, TecDoc = 483, BrandName = "ClimAir", IsActive = true, BrandDescription = "" },
                new Brand { Id = 187, TecDoc = 485, BrandName = "NARVA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 188, TecDoc = 494, BrandName = "BRISK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 189, TecDoc = 499, BrandName = "ZAFFO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 190, TecDoc = 4005, BrandName = "EPS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 191, TecDoc = 4006, BrandName = "KW", IsActive = true, BrandDescription = "" },
                new Brand { Id = 192, TecDoc = 4023, BrandName = "KS TOOLS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 193, TecDoc = 4026, BrandName = "VIGOR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 194, TecDoc = 4314, BrandName = "SHELL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 195, TecDoc = 4333, BrandName = "Prestone", IsActive = true, BrandDescription = "" },
                new Brand { Id = 196, TecDoc = 4344, BrandName = "ELTA AUTOMOTIVE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 197, TecDoc = 4346, BrandName = "vika", IsActive = true, BrandDescription = "" },
                new Brand { Id = 198, TecDoc = 4353, BrandName = "DPA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 199, TecDoc = 4367, BrandName = "STOP&GO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 200, TecDoc = 4372, BrandName = "PETEC", IsActive = true, BrandDescription = "" },
                new Brand { Id = 201, TecDoc = 4381, BrandName = "Airstal", IsActive = true, BrandDescription = "" },
                new Brand { Id = 202, TecDoc = 4434, BrandName = "CONTINENTAL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 203, TecDoc = 4436, BrandName = "DUNLOP", IsActive = true, BrandDescription = "" },
                new Brand { Id = 204, TecDoc = 4449, BrandName = "MOBIL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 205, TecDoc = 4451, BrandName = "YUASA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 206, TecDoc = 4452, BrandName = "GS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 207, TecDoc = 4457, BrandName = "SONAX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 208, TecDoc = 4512, BrandName = "ERT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 209, TecDoc = 4514, BrandName = "ET ENGINETEAM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 210, TecDoc = 4536, BrandName = "LINEX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 211, TecDoc = 4539, BrandName = "Arnott", IsActive = true, BrandDescription = "" },
                new Brand { Id = 212, TecDoc = 4593, BrandName = "TEDGUM", IsActive = true, BrandDescription = "" },
                new Brand { Id = 213, TecDoc = 4612, BrandName = "GE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 214, TecDoc = 4615, BrandName = "GARRETT", IsActive = true, BrandDescription = "" },
                new Brand { Id = 215, TecDoc = 4657, BrandName = "ABAKUS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 216, TecDoc = 4676, BrandName = "ROTINGER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 217, TecDoc = 4679, BrandName = "CAFFARO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 218, TecDoc = 4705, BrandName = "MOBILETRON", IsActive = true, BrandDescription = "" },
                new Brand { Id = 219, TecDoc = 4717, BrandName = "NE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 220, TecDoc = 4719, BrandName = "LIFT-TEK", IsActive = true, BrandDescription = "" },
                new Brand { Id = 221, TecDoc = 4721, BrandName = "MIRAGLIO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 222, TecDoc = 4734, BrandName = "HELLA GUTMANN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 223, TecDoc = 4808, BrandName = "HAZET", IsActive = true, BrandDescription = "" },
                new Brand { Id = 224, TecDoc = 4815, BrandName = "Borsehung", IsActive = true, BrandDescription = "" },
                new Brand { Id = 225, TecDoc = 4821, BrandName = "QUARO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 226, TecDoc = 4843, BrandName = "AS-PL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 227, TecDoc = 4849, BrandName = "Ac Rolcar", IsActive = true, BrandDescription = "" },
                new Brand { Id = 228, TecDoc = 4866, BrandName = "ARAL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 229, TecDoc = 4871, BrandName = "COFLE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 230, TecDoc = 4873, BrandName = "POLMO", IsActive = true, BrandDescription = "" },
                new Brand { Id = 231, TecDoc = 4881, BrandName = "DYNAMAX", IsActive = true, BrandDescription = "" },
                new Brand { Id = 232, TecDoc = 4911, BrandName = "ALLIGATOR", IsActive = true, BrandDescription = "" },
                new Brand { Id = 233, TecDoc = 4912, BrandName = "GEDORE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 234, TecDoc = 4923, BrandName = "NORMA", IsActive = true, BrandDescription = "" },
                new Brand { Id = 235, TecDoc = 4946, BrandName = "SCHRADER", IsActive = true, BrandDescription = "" },
                new Brand { Id = 236, TecDoc = 4949, BrandName = "TURBORAIL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 237, TecDoc = 4969, BrandName = "ESEN SKV", IsActive = true, BrandDescription = "" },
                new Brand { Id = 238, TecDoc = 5251, BrandName = "HART", IsActive = true, BrandDescription = "" },
                new Brand { Id = 239, TecDoc = 6102, BrandName = "ACPS-ORIS", IsActive = true, BrandDescription = "" },
                new Brand { Id = 240, TecDoc = 6186, BrandName = "VALVOLINE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 241, TecDoc = 6263, BrandName = "CPB", IsActive = true, BrandDescription = "" },
                new Brand { Id = 242, TecDoc = 6304, BrandName = "QUICK BRAKE", IsActive = true, BrandDescription = "" },
                new Brand { Id = 243, TecDoc = 6306, BrandName = "GKN", IsActive = true, BrandDescription = "" },
                new Brand { Id = 244, TecDoc = 6343, BrandName = "REPSOL", IsActive = true, BrandDescription = "" },
                new Brand { Id = 245, TecDoc = 6368, BrandName = "EBC Brakes", IsActive = true, BrandDescription = "" },
                new Brand { Id = 246, TecDoc = 6441, BrandName = "BERU by DRiV", IsActive = true, BrandDescription = "" },
                new Brand { Id = 247, TecDoc = 6444, BrandName = "BorgWarner (AWD)", IsActive = true, BrandDescription = "" },
                new Brand { Id = 248, TecDoc = 6534, BrandName = "Dr.Motor Automotive", IsActive = true, BrandDescription = "" },
                new Brand { Id = 249, TecDoc = 6558, BrandName = "AIC", IsActive = true, BrandDescription = "" },
                new Brand { Id = 250, TecDoc = 6984, BrandName = "Oyodo", IsActive = true, BrandDescription = "" },
                new Brand { Id = 251, TecDoc = 6985, BrandName = "JPN", IsActive = true, BrandDescription = "" }
                );
        }
    }
}