using AutopartsEntity.Catalog.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AutopartsRepository.Configurations.Catalog
{
    public class ManufacturerConfig : IEntityTypeConfiguration<Manufacturer>
    {
        public void Configure(EntityTypeBuilder<Manufacturer> builder)
        {
            builder.Property(x => x.CreateDate).IsRequired()
                .HasMaxLength(10);
            builder.Property(x => x.UpdateDate)
                .HasMaxLength(10);
            builder.Property(x => x.RowVersion)
                .IsRowVersion();

            builder.Property(x => x.TecDoc)
                .HasMaxLength(6);
            builder.Property(x => x.Title).IsRequired()
                .HasMaxLength(50);
            builder.Property(x => x.LogoPath)
                .HasMaxLength(500);
            builder.Property(x => x.Description)
                .HasMaxLength(2000);
            builder.Property(x => x.IsAutoParts)
                .HasDefaultValue(false);
            builder.Property(x => x.IsPKW)
                .HasDefaultValue(false);
            builder.Property(x => x.IsLKW)
                .HasDefaultValue(false);
            builder.Property(x => x.IsMotorcycle)
                .HasDefaultValue(false);
            builder.Property(x => x.IsAgriculturalMachinery)
                .HasDefaultValue(false);
            builder.Property(x => x.IsCompressors)
                .HasDefaultValue(false);
            builder.Property(x => x.IsConstuctionAndMining)
                .HasDefaultValue(false);
            builder.Property(x => x.IsElectronicDischargeMachines)
                .HasDefaultValue(false);
            builder.Property(x => x.IsEngines)
                .HasDefaultValue(false);
            builder.Property(x => x.IsForkLiftTruck)
                .HasDefaultValue(false);
            builder.Property(x => x.IsIndustrialApplications)
                .HasDefaultValue(false);
            builder.Property(x => x.IsShipsAndBoats)
                .HasDefaultValue(false);
            builder.Property(x => x.IsVacuumPumps)
                .HasDefaultValue(false);
            builder.Property(x => x.IsActive)
                .HasDefaultValue(false);

            builder.HasData(
                new Manufacturer { Id = 1, TecDoc = 3854, Title = "ABARTH", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 2, TecDoc = 1480, Title = "AIXAM", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 3, TecDoc = 2, Title = "ALFA ROMEO", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 4, TecDoc = 1360, Title = "ARO", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 5, TecDoc = 881, Title = "ASTON MARTIN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 6, TecDoc = 5, Title = "AUDI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 7, TecDoc = 6, Title = "AUSTIN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 8, TecDoc = 799, Title = "AUTOBIANCHI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 9, TecDoc = 815, Title = "BENTLEY", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 10, TecDoc = 16, Title = "BMW", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 11, TecDoc = 788, Title = "BUGATTI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 12, TecDoc = 816, Title = "BUICK", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 13, TecDoc = 819, Title = "CADILLAC", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 14, TecDoc = 21, Title = "CITROËN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 15, TecDoc = 139, Title = "DACIA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 16, TecDoc = 185, Title = "DAEWOO", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 17, TecDoc = 24, Title = "DAF", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 18, TecDoc = 25, Title = "DAIHATSU", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 19, TecDoc = 29, Title = "DODGE", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 20, TecDoc = 4468, Title = "DS", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 21, TecDoc = 3332, Title = "EMGRAND", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 22, TecDoc = 700, Title = "FERRARI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 23, TecDoc = 35, Title = "FIAT", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 24, TecDoc = 36, Title = "FORD", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 25, TecDoc = 776, Title = "FORD USA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 26, TecDoc = 148, Title = "GAZ", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 27, TecDoc = 2590, Title = "GEELY", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 28, TecDoc = 831, Title = "GEO", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 29, TecDoc = 2903, Title = "GREAT WALL", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 30, TecDoc = 45, Title = "HONDA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 31, TecDoc = 1506, Title = "HUMMER", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 32, TecDoc = 183, Title = "HYUNDAI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 33, TecDoc = 2887, Title = "CHERY", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 34, TecDoc = 138, Title = "CHEVROLET", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 35, TecDoc = 20, Title = "CHRYSLER", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 36, TecDoc = 1526, Title = "INFINITI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 37, TecDoc = 54, Title = "ISUZU", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 38, TecDoc = 55, Title = "IVECO", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 39, TecDoc = 56, Title = "JAGUAR", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 40, TecDoc = 882, Title = "JEEP", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 41, TecDoc = 184, Title = "KIA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 42, TecDoc = 2760, Title = "KTM", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 43, TecDoc = 63, Title = "LADA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 44, TecDoc = 701, Title = "LAMBORGHINI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 45, TecDoc = 64, Title = "LANCIA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 46, TecDoc = 1820, Title = "LAND ROVER", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 47, TecDoc = 1380, Title = "LDV", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 48, TecDoc = 842, Title = "LEXUS", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 49, TecDoc = 1200, Title = "LINCOLN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 50, TecDoc = 802, Title = "LOTUS", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 51, TecDoc = 69, Title = "MAN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 52, TecDoc = 771, Title = "MASERATI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 53, TecDoc = 72, Title = "MAZDA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 54, TecDoc = 74, Title = "MERCEDES-BENZ", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 55, TecDoc = 75, Title = "MG", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 56, TecDoc = 1523, Title = "MINI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 57, TecDoc = 77, Title = "MITSUBISHI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 58, TecDoc = 813, Title = "MOSKVICH", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 59, TecDoc = 80, Title = "NISSAN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 60, TecDoc = 84, Title = "OPEL", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 61, TecDoc = 88, Title = "PEUGEOT", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 62, TecDoc = 850, Title = "PLYMOUTH", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 63, TecDoc = 774, Title = "PONTIAC", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 64, TecDoc = 92, Title = "PORSCHE", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 65, TecDoc = 778, Title = "PROTON", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 66, TecDoc = 93, Title = "RENAULT", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 67, TecDoc = 694, Title = "RENAULT TRUCKS", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 68, TecDoc = 705, Title = "ROLLS-ROYCE", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 69, TecDoc = 95, Title = "ROVER", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 70, TecDoc = 99, Title = "SAAB", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 71, TecDoc = 104, Title = "SEAT", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 72, TecDoc = 106, Title = "ŠKODA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 73, TecDoc = 1138, Title = "SMART", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 74, TecDoc = 175, Title = "SSANGYONG", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 75, TecDoc = 107, Title = "SUBARU", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 76, TecDoc = 109, Title = "SUZUKI", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 77, TecDoc = 110, Title = "TALBOT", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 78, TecDoc = 3328, Title = "TESLA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 79, TecDoc = 111, Title = "TOYOTA", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 80, TecDoc = 187, Title = "TRABANT", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 81, TecDoc = 121, Title = "VOLKSWAGEN", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 82, TecDoc = 120, Title = "VOLVO", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true },
                new Manufacturer { Id = 83, TecDoc = 186, Title = "WARTBURG", IsAutoParts = false, IsPKW = true, IsLKW = false, IsMotorcycle = false, IsAgriculturalMachinery = false, IsCompressors = false, IsConstuctionAndMining = false, IsElectronicDischargeMachines = false, IsEngines = false, IsForkLiftTruck = false, IsIndustrialApplications = false, IsShipsAndBoats = false, IsVacuumPumps = false, IsActive = true }
                );
        }
    }
}